// 시드 단어 데이터 (처음 실행 시 자동으로 단어장에 채워집니다)
// term: 영어 단어 / meaning: 뜻 / example: 영어 예문 / exampleKo: 예문 해석 / tags: 분류
window.SEED_WORDS = [
  { term: "abandon", meaning: "버리다, 포기하다", example: "They had to abandon the car in the snow.", exampleKo: "그들은 눈 속에 차를 버려야 했다.", tags: ["기본"] },
  { term: "ability", meaning: "능력, 재능", example: "She has the ability to solve hard problems.", exampleKo: "그녀는 어려운 문제를 푸는 능력이 있다.", tags: ["기본"] },
  { term: "achieve", meaning: "달성하다, 성취하다", example: "He worked hard to achieve his goal.", exampleKo: "그는 목표를 이루기 위해 열심히 일했다.", tags: ["기본"] },
  { term: "acquire", meaning: "얻다, 습득하다", example: "You can acquire new skills through practice.", exampleKo: "연습을 통해 새로운 기술을 습득할 수 있다.", tags: ["중급"] },
  { term: "adapt", meaning: "적응하다, 조정하다", example: "Animals adapt to their environment.", exampleKo: "동물들은 환경에 적응한다.", tags: ["중급"] },
  { term: "adequate", meaning: "충분한, 적절한", example: "We need adequate time to finish the task.", exampleKo: "그 일을 끝내려면 충분한 시간이 필요하다.", tags: ["중급"] },
  { term: "afford", meaning: "~할 여유가 있다", example: "I can't afford a new phone right now.", exampleKo: "지금은 새 휴대폰을 살 여유가 없다.", tags: ["기본"] },
  { term: "analyze", meaning: "분석하다", example: "We need to analyze the data carefully.", exampleKo: "우리는 데이터를 신중하게 분석해야 한다.", tags: ["중급"] },
  { term: "anticipate", meaning: "예상하다, 기대하다", example: "We anticipate a busy weekend.", exampleKo: "우리는 바쁜 주말을 예상한다.", tags: ["고급"] },
  { term: "apparent", meaning: "명백한, 분명한", example: "It was apparent that he was tired.", exampleKo: "그가 피곤하다는 것이 분명했다.", tags: ["중급"] },
  { term: "appreciate", meaning: "감사하다, 진가를 알아보다", example: "I really appreciate your help.", exampleKo: "당신의 도움에 정말 감사합니다.", tags: ["기본"] },
  { term: "approach", meaning: "접근하다; 접근법", example: "Let's try a different approach.", exampleKo: "다른 접근법을 시도해 보자.", tags: ["기본"] },
  { term: "appropriate", meaning: "적절한, 알맞은", example: "Please wear appropriate clothes.", exampleKo: "적절한 옷을 입어 주세요.", tags: ["중급"] },
  { term: "assume", meaning: "가정하다, 추정하다", example: "Don't assume you know the answer.", exampleKo: "네가 답을 안다고 단정하지 마.", tags: ["중급"] },
  { term: "attempt", meaning: "시도하다; 시도", example: "She made an attempt to fix it.", exampleKo: "그녀는 그것을 고치려고 시도했다.", tags: ["기본"] },
  { term: "available", meaning: "이용 가능한, 시간이 되는", example: "Are you available tomorrow?", exampleKo: "내일 시간 되세요?", tags: ["기본"] },
  { term: "aware", meaning: "알고 있는, 인식하는", example: "I wasn't aware of the change.", exampleKo: "나는 그 변화를 알지 못했다.", tags: ["기본"] },
  { term: "benefit", meaning: "이익, 혜택; 유익하다", example: "Exercise has many health benefits.", exampleKo: "운동은 많은 건강상의 이점이 있다.", tags: ["기본"] },
  { term: "capable", meaning: "능력 있는, ~할 수 있는", example: "She is capable of great things.", exampleKo: "그녀는 대단한 일을 해낼 수 있다.", tags: ["중급"] },
  { term: "challenge", meaning: "도전; 도전하다", example: "Learning English is a fun challenge.", exampleKo: "영어를 배우는 것은 즐거운 도전이다.", tags: ["기본"] },
  { term: "circumstance", meaning: "상황, 환경", example: "Under these circumstances, we must wait.", exampleKo: "이런 상황에서는 기다려야 한다.", tags: ["고급"] },
  { term: "commit", meaning: "저지르다, 헌신하다", example: "He committed to the new project.", exampleKo: "그는 새 프로젝트에 전념했다.", tags: ["중급"] },
  { term: "compare", meaning: "비교하다", example: "Let's compare the two options.", exampleKo: "두 가지 선택을 비교해 보자.", tags: ["기본"] },
  { term: "complex", meaning: "복잡한", example: "This is a complex situation.", exampleKo: "이것은 복잡한 상황이다.", tags: ["중급"] },
  { term: "concept", meaning: "개념", example: "The concept is easy to understand.", exampleKo: "그 개념은 이해하기 쉽다.", tags: ["중급"] },
  { term: "consider", meaning: "고려하다, 여기다", example: "Please consider my suggestion.", exampleKo: "제 제안을 고려해 주세요.", tags: ["기본"] },
  { term: "consistent", meaning: "일관된, 꾸준한", example: "Be consistent with your studies.", exampleKo: "공부를 꾸준히 하세요.", tags: ["중급"] },
  { term: "contribute", meaning: "기여하다, 기부하다", example: "Everyone can contribute ideas.", exampleKo: "모두가 아이디어를 낼 수 있다.", tags: ["중급"] },
  { term: "convince", meaning: "설득하다, 확신시키다", example: "He convinced me to join.", exampleKo: "그는 나를 참여하도록 설득했다.", tags: ["중급"] },
  { term: "crucial", meaning: "결정적인, 중대한", example: "This step is crucial for success.", exampleKo: "이 단계는 성공에 결정적이다.", tags: ["고급"] },
  { term: "define", meaning: "정의하다", example: "Can you define this word?", exampleKo: "이 단어를 정의할 수 있나요?", tags: ["기본"] },
  { term: "demonstrate", meaning: "보여주다, 증명하다", example: "She demonstrated the new method.", exampleKo: "그녀는 새로운 방법을 시연했다.", tags: ["중급"] },
  { term: "determine", meaning: "결정하다, 밝혀내다", example: "We must determine the cause.", exampleKo: "우리는 원인을 밝혀내야 한다.", tags: ["중급"] },
  { term: "distinguish", meaning: "구별하다", example: "It's hard to distinguish the twins.", exampleKo: "그 쌍둥이를 구별하기 어렵다.", tags: ["고급"] },
  { term: "efficient", meaning: "효율적인", example: "This is a more efficient way.", exampleKo: "이것이 더 효율적인 방법이다.", tags: ["중급"] },
  { term: "emphasize", meaning: "강조하다", example: "The teacher emphasized the main point.", exampleKo: "선생님은 요점을 강조했다.", tags: ["고급"] },
  { term: "encounter", meaning: "마주치다; 만남", example: "We encountered a problem.", exampleKo: "우리는 문제에 부딪혔다.", tags: ["중급"] },
  { term: "essential", meaning: "필수적인", example: "Water is essential for life.", exampleKo: "물은 생명에 필수적이다.", tags: ["기본"] },
  { term: "establish", meaning: "설립하다, 확립하다", example: "They established a new company.", exampleKo: "그들은 새 회사를 설립했다.", tags: ["중급"] },
  { term: "estimate", meaning: "추정하다; 추정치", example: "Can you estimate the cost?", exampleKo: "비용을 추정할 수 있나요?", tags: ["중급"] },
  { term: "eventually", meaning: "결국, 마침내", example: "She eventually passed the test.", exampleKo: "그녀는 결국 시험에 합격했다.", tags: ["기본"] },
  { term: "evidence", meaning: "증거", example: "There is no evidence for that.", exampleKo: "그것에 대한 증거는 없다.", tags: ["기본"] },
  { term: "familiar", meaning: "익숙한, 친숙한", example: "This song sounds familiar.", exampleKo: "이 노래는 익숙하게 들린다.", tags: ["기본"] },
  { term: "flexible", meaning: "유연한, 융통성 있는", example: "My schedule is flexible.", exampleKo: "내 일정은 유연하다.", tags: ["중급"] },
  { term: "fundamental", meaning: "근본적인, 기본적인", example: "These are the fundamental rules.", exampleKo: "이것들이 기본 규칙이다.", tags: ["고급"] },
  { term: "generate", meaning: "생성하다, 발생시키다", example: "The plan will generate profit.", exampleKo: "그 계획은 이익을 낼 것이다.", tags: ["중급"] },
  { term: "genuine", meaning: "진짜의, 진심의", example: "She has a genuine interest in art.", exampleKo: "그녀는 예술에 진심 어린 관심이 있다.", tags: ["고급"] },
  { term: "identify", meaning: "확인하다, 식별하다", example: "Can you identify this bird?", exampleKo: "이 새를 식별할 수 있나요?", tags: ["기본"] },
  { term: "impact", meaning: "영향; 영향을 주다", example: "The news had a big impact.", exampleKo: "그 소식은 큰 영향을 미쳤다.", tags: ["기본"] },
  { term: "implement", meaning: "시행하다, 실행하다", example: "We will implement the new plan.", exampleKo: "우리는 새 계획을 시행할 것이다.", tags: ["고급"] },
  { term: "indicate", meaning: "나타내다, 가리키다", example: "The sign indicates the exit.", exampleKo: "그 표지판은 출구를 가리킨다.", tags: ["중급"] },
  { term: "influence", meaning: "영향; 영향을 미치다", example: "Friends can influence your choices.", exampleKo: "친구들이 네 선택에 영향을 줄 수 있다.", tags: ["기본"] },
  { term: "maintain", meaning: "유지하다, 주장하다", example: "It's important to maintain balance.", exampleKo: "균형을 유지하는 것이 중요하다.", tags: ["중급"] },
  { term: "obvious", meaning: "명백한, 뻔한", example: "The answer is obvious.", exampleKo: "답은 명백하다.", tags: ["기본"] },
  { term: "occur", meaning: "일어나다, 발생하다", example: "The accident occurred at night.", exampleKo: "그 사고는 밤에 일어났다.", tags: ["중급"] },
  { term: "participate", meaning: "참여하다", example: "Everyone can participate in the game.", exampleKo: "모두가 게임에 참여할 수 있다.", tags: ["기본"] },
  { term: "perceive", meaning: "인지하다, 감지하다", example: "How do you perceive the situation?", exampleKo: "그 상황을 어떻게 인식하세요?", tags: ["고급"] },
  { term: "priority", meaning: "우선순위", example: "Safety is our top priority.", exampleKo: "안전이 우리의 최우선이다.", tags: ["중급"] },
  { term: "reliable", meaning: "믿을 수 있는", example: "He is a reliable friend.", exampleKo: "그는 믿을 수 있는 친구다.", tags: ["중급"] },
  { term: "significant", meaning: "중요한, 상당한", example: "There was a significant change.", exampleKo: "상당한 변화가 있었다.", tags: ["중급"] },
  { term: "sufficient", meaning: "충분한", example: "We have sufficient food for the trip.", exampleKo: "여행에 충분한 음식이 있다.", tags: ["고급"] },
  { term: "tend", meaning: "~하는 경향이 있다", example: "I tend to wake up early.", exampleKo: "나는 일찍 일어나는 경향이 있다.", tags: ["중급"] },
  { term: "thorough", meaning: "철저한, 빈틈없는", example: "She did a thorough job.", exampleKo: "그녀는 철저하게 일했다.", tags: ["고급"] },
  { term: "virtually", meaning: "사실상, 거의", example: "The task is virtually complete.", exampleKo: "그 일은 사실상 완료되었다.", tags: ["고급"] }
];
